language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - libx11-dev
            - libgl1-mesa-dev
            - libglu1-mesa-dev
            - xorg-dev
      env:
        - MATRIX_EVAL="CXX=g++-7"
before_install:
  - eval "${MATRIX_EVAL}"
script:
  - git submodule update --init
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .