name: Windows

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        choco install ninja
        choco install git.install --params "/GitAndUnixToolsOnPath"
    - name: download submodule
      run: git submodule update --init
    - name: cmake configure
      run: |
        mkdir build
        cd build
        cmake ..
    - name: build
      run: cmake --build .
      working-directory: build
